### ISSUE TITLE
[Feat] 지난 경매 리스트 및 작품 조회

### ISSUE THREAD

**Issue by Gyubam** [Senier-Project-Trade-Platform/backend#138]
## 📌  Description
- 홈 화면에서 지난 경매 리스트 및 해당 경매 작품을 확인할 수 있습니다.
## 📝  To-do
- [x] 지난 경매 리스트 조회 api
- [x] #139

![image](https://user-images.githubusercontent.com/71515740/215064684-b4a99a75-6497-4f62-8db4-54cedbc235ac.png)

![image](https://user-images.githubusercontent.com/71515740/215064971-e71294f4-867c-458a-8f1d-13a3ca361c4f.png)

**Comment by guesung** [comment]
오잉 무슨 버튼이지 하다가 실수로 convert to issue 눌렀습니다 ㅜㅜ
